#!/usr/bin/env python
#
# -*- coding: CP1252 -*-
#
# generated by wxGlade 9756a246126b on Fri Aug 31 21:11:34 2012
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade
from tudi_panel import TudiPanel
from tudi_listctrl import ProteinList
# begin wxGlade: extracode
# end wxGlade


class TudiFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TudiFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.win_2 = wx.SplitterWindow(self, wx.ID_ANY, style=wx.SP_3D | wx.SP_BORDER)
        self.panel_1 = wx.Panel(self.win_2, wx.ID_ANY)
        self.view = TudiPanel(self.panel_1, wx.ID_ANY)
        self.win_2_pane = wx.Panel(self.win_2, wx.ID_ANY)
        self.lb_file = wx.StaticText(self.win_2_pane, wx.ID_ANY, "Input File")
        self.cbx_file = wx.ComboBox(self.win_2_pane, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.bt_file = wx.Button(self.win_2_pane, wx.ID_ANY, "open")
        self.lb_proteins = wx.StaticText(self.win_2_pane, wx.ID_ANY, "Proteins")
        self.proteins = ProteinList(self.win_2_pane, wx.ID_ANY)
        self.bt_about = wx.Button(self.win_2_pane, wx.ID_ANY, "- made at lp csic/uab -  ", style=wx.NO_BORDER)
        self.sl_1 = wx.StaticLine(self.win_2_pane, wx.ID_ANY, style=wx.LI_VERTICAL)
        self.rb_id = wx.RadioButton(self.win_2_pane, wx.ID_ANY, " ID ", style=wx.RB_GROUP)
        self.rb_name = wx.RadioButton(self.win_2_pane, wx.ID_ANY, "Name")
        self.tc_search = wx.TextCtrl(self.win_2_pane, wx.ID_ANY, "")
        self.bt_search = wx.Button(self.win_2_pane, wx.ID_ANY, "search")
        self.bt_clear_list = wx.Button(self.win_2_pane, wx.ID_ANY, "unmark")
        self.szr_22_staticbox = wx.StaticBox(self.win_2_pane, wx.ID_ANY, "")
        self.grid_picked = wx.grid.Grid(self.win_2_pane, wx.ID_ANY, size=(1, 1))
        self.szr_23_staticbox = wx.StaticBox(self.win_2_pane, wx.ID_ANY, "mouse hits")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TudiFrame.__set_properties
        #self.SetTitle("Tudi_Viewer")
        self.SetBackgroundColour(wx.Colour(255, 251, 159))
        self.cbx_file.SetMinSize((-1, -1))
        self.bt_file.SetMinSize((50, -1))
        self.proteins.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.bt_about.SetMinSize((159, 20))
        self.bt_about.SetBackgroundColour(wx.Colour(255, 218, 90))
        self.bt_about.SetFont(wx.Font(8, wx.DEFAULT, wx.ITALIC, wx.NORMAL, 0, ""))
        self.rb_id.SetValue(1)
        self.tc_search.SetMinSize((150, 23))
        self.bt_search.SetMinSize((50, -1))
        self.bt_clear_list.SetMinSize((50, -1))
        self.grid_picked.CreateGrid(3, 3)
        self.grid_picked.SetRowLabelSize(25)
        self.grid_picked.SetColLabelSize(15)
        self.grid_picked.EnableEditing(0)
        self.grid_picked.EnableDragRowSize(0)
        self.grid_picked.SetSelectionMode(wx.grid.Grid.wxGridSelectRows)
        self.grid_picked.SetColLabelValue(0, "#")
        self.grid_picked.SetColSize(0, 10)
        self.grid_picked.SetColLabelValue(1, "ID")
        self.grid_picked.SetColLabelValue(2, "NAME")
        self.grid_picked.SetColSize(2, 400)
        self.grid_picked.SetMinSize((-1, 100))
        self.win_2_pane.SetBackgroundColour(wx.Colour(175, 255, 183))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TudiFrame.__do_layout
        szr_1 = wx.BoxSizer(wx.VERTICAL)
        szr_2 = wx.BoxSizer(wx.VERTICAL)
        self.szr_23_staticbox.Lower()
        szr_23 = wx.StaticBoxSizer(self.szr_23_staticbox, wx.VERTICAL)
        self.szr_22_staticbox.Lower()
        szr_22 = wx.StaticBoxSizer(self.szr_22_staticbox, wx.VERTICAL)
        szr_221 = wx.BoxSizer(wx.HORIZONTAL)
        szr_21 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.view, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_1)
        szr_21.Add(self.lb_file, 0, wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 5)
        szr_21.Add(self.cbx_file, 1, wx.TOP | wx.EXPAND, 3)
        szr_21.Add(self.bt_file, 0, 0, 0)
        szr_2.Add(szr_21, 0, wx.ALL | wx.EXPAND, 5)
        szr_22.Add(self.lb_proteins, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        szr_22.Add(self.proteins, 1, wx.ALL | wx.EXPAND, 5)
        szr_221.Add(self.bt_about, 0, wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 5)
        szr_221.Add(self.sl_1, 0, wx.LEFT | wx.RIGHT | wx.EXPAND, 5)
        szr_221.Add(self.rb_id, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 6)
        szr_221.Add(self.rb_name, 0, wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 3)
        szr_221.Add(self.tc_search, 1, wx.EXPAND, 0)
        szr_221.Add(self.bt_search, 0, 0, 0)
        szr_221.Add(self.bt_clear_list, 0, 0, 0)
        szr_22.Add(szr_221, 0, wx.EXPAND, 0)
        szr_2.Add(szr_22, 1, wx.EXPAND, 0)
        szr_23.Add(self.grid_picked, 0, wx.ALL | wx.EXPAND, 5)
        szr_2.Add(szr_23, 0, wx.EXPAND, 0)
        self.win_2_pane.SetSizer(szr_2)
        self.win_2.SplitVertically(self.panel_1, self.win_2_pane)
        szr_1.Add(self.win_2, 1, wx.ALL | wx.EXPAND, 5)
        self.SetSizer(szr_1)
        szr_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class TudiFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_3 = TudiFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_3)
    frame_3.Show()
    app.MainLoop()
